# Generated by Django 4.0.6 on 2022-07-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalHoroscopeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_sign_no', models.IntegerField()),
                ('zodiac_name', models.CharField(max_length=200)),
                ('zodiac_image', models.ImageField(upload_to='Zodiac_Images/')),
                ('zodiac_sign_image', models.ImageField(upload_to='Zodiac_Sign_Images/')),
                ('zodiac_carousel', models.ImageField(upload_to='Zodiac_Carousel_Images/')),
            ],
        ),
    ]
