from django.urls import path
from . import views
from django.contrib import admin
app_name='MyZodiacSigns'
urlpatterns=[
    path('',views.HomePageView,name="HomePage"),
    path('About/',views.AboutPageView,name="AboutPage"),
    path('DailyHoroscopes/',views.DailyHoroscopeDetailView,name="DailyHoroscopes"),
    path('TomorrowHoroscopes/',views.TomorrowHoroscopeDetailView,name='TomorrowHoroscopes'),
    path('WeeklyHoroscopes/',views.WeeklyHoroscopeDetailView,name='WeeklyHoroscopes'),
    path('MonthlyHoroscopes/',views.MonthlyHoroscopeDetailView,name="MonthlyHoroscopes"),
    path('YearlyHoroscopes/',views.YearlyHoroscopeDetailView,name='YearlyHoroscopes'),
    path('ZodiacSignFindings/',views.FindZodiacDetailView,name='ZodiacSignFindings'),
    path('LoveCompatibility/',views.ZodiacLoveCompatibilityDetailView,name="LoveCompatibility"),

    path('BirthdayDetails/General/',views.TodayBirthdateGeneralHoroscopeDetailView, name='TodayGeneralBirthday'),
    path('BirthdayDetails/GiftIdeas/',views.TodayBirthdateGiftDetailView, name='TodayBirthGiftDetails'),
    path('BirthdayDetails/PamperingIdeas/',views.TodayBirthdatePamperingDetailView, name='TodayBirthPamperingDetails'),
    path('BirthdayDetails/PartyIdeas/',views.TodayBirthdatePartyDetailView, name='TodayBirthPartyDetails'),
    path('BirthdayDetails/DestinationIdeas/',views.TodayBirthdateDestinationsDetailView, name='TodayBirthDestinationDetails'),
    path('BirthDatewise/GeneralOverallDetails/',views.DateWiseBirthDateGeneralOverallDetailView,name='DatewiseGeneralOverallDetails'),

    path('OverallHoroscopes/',views.OverallZodiacHoroscopesDetailView, name='OverallHoroscopeDetails'),
    path('OverallHoroscopes/AriesHoroscopes/',views.AriesHoroscopeDetailView, name='AriesHoroscopeDetails'),
    path('OverallHoroscopes/TaurusHoroscopes/',views.TaurusHoroscopeDetailView, name='TaurusHoroscopeDetails'),
    path('OverallHoroscopes/GeminiHoroscopes/',views.GeminiHoroscopeDetailView, name='GeminiHoroscopeDetails'),
    path('OverallHoroscopes/CancerHoroscopes/',views.CancerHoroscopeDetailView, name='CancerHoroscopeDetails'),
    path('OverallHoroscopes/LeoHoroscopes/',views.LeoHoroscopeDetailView,name="LeoHoroscopeDetails"),
    path('OverallHoroscopes/VirgoHoroscopes/',views.VirgoHoroscopeDetailView,name="VirgoHoroscopeDetails"),
    path('OverallHoroscopes/LibraHoroscopes/',views.LibraHoroscopeDetailView,name="LibraHoroscopeDetails"),
    path('OverallHoroscopes/ScorpioHoroscopes/',views.ScorpioHoroscopeDetailView,name="ScorpioHoroscopeDetails"),
    path('OverallHoroscopes/SagittariusHoroscopes/',views.SagittariusHoroscopeDetailView,name="SagittariusHoroscopeDetails"),
    path('OverallHoroscopes/CapricornHoroscopes/',views.CapricornHoroscopeDetailView,name="CapricornHoroscopeDetails"),
    path('OverallHoroscopes/AquariusHoroscopes/',views.AquariusHoroscopeDetailView,name="AquariusHoroscopeDetails"),
    path('OverallHoroscopes/PiscesHoroscopes/',views.PiscesHoroscopeDetailView,name="PiscesHoroscopeDetails"),
    
    path('AriesBasicZodiacDetails/',views.AriesBasicZodiacDetailView,name='AriesBasicZodiacDetails'),
    path('TaurusBasicZodiacDetails/',views.TaurusBasicZodiacDetailView,name='TaurusBasicZodiacDetails'),
    path('GeminiBasicZodiacDetails/',views.GeminiBasicZodiacDetailView,name='GeminiBasicZodiacDetails'),
    path('CancerBasicZodiacDetails/',views.CancerBasicZodiacDetailView,name='CancerBasicZodiacDetails'),
    path('LeoBasicZodiacDetails/',views.LeoBasicZodiacDetailView,name='LeoBasicZodiacDetails'),
    path('VirgoBasicZodiacDetails/',views.VirgoBasicZodiacDetailView,name='VirgoBasicZodiacDetails'),
    path('LibraBasicZodiacDetails/',views.LibraBasicZodiacDetailView,name='LibraBasicZodiacDetails'),
    path('ScorpioBasicZodiacDetails/',views.ScorpioBasicZodiacDetailView,name='ScorpioBasicZodiacDetails'),
    path('SagittariusBasicZodiacDetails/',views.SagittariusBasicZodiacDetailView,name='SagittariusBasicZodiacDetails'),
    path('CapricornBasicZodiacDetails/',views.CapricornBasicZodiacDetailView,name='CapricornBasicZodiacDetails'),
    path('AquariusBasicZodiacDetails/',views.AquariusBasicZodiacDetailView,name='AquariusBasicZodiacDetails'),
    path('PiscesBasicZodiacDetails/',views.PiscesBasicZodiacDetailView,name='PiscesBasicZodiacDetails'),
    
    path('ZodiacOverallview/',views.OverallZodiacOverviewDetailView,name='OverallZodiacOverviewDetails'),
    path('ZodiacOverallview/AriesZodiac/',views.AriesZodiacOverviewDetailView,name='AriesZodiacOverview'),
    path('ZodiacOverallview/TaurusZodiac/',views.TaurusZodiacOverviewDetailView,name='TaurusZodiacOverview'),
    path('ZodiacOverallview/GeminiZodiac/',views.GeminiZodiacOverviewDetailView,name='GeminiZodiacOverview'),
    path('ZodiacOverallview/CancerZodiac/',views.CancerZodiacOverviewDetailView,name='CancerZodiacOverview'),
    path('ZodiacOverallview/LeoZodiac/',views.LeoZodiacOverviewDetailView,name='LeoZodiacOverview'),
    path('ZodiacOverallview/VirgoZodiac/',views.VirgoZodiacOverviewDetailView,name='VirgoZodiacOverview'),
    path('ZodiacOverallview/LibraZodiac/',views.LibraZodiacOverviewDetailView,name='LibraZodiacOverview'),
    path('ZodiacOverallview/ScorpioZodiac/',views.ScorpioZodiacOverviewDetailView,name='ScorpioZodiacOverview'),
    path('ZodiacOverallview/SagittariusZodiac/',views.SagittariusZodiacOverviewDetailView,name='SagittariusZodiacOverview'),
    path('ZodiacOverallview/CapricornZodiac/',views.CapricornZodiacOverviewDetailView,name='CapricornZodiacOverview'),
    path('ZodiacOverallview/AquariusZodiac/',views.AquariusZodiacOverviewDetailView,name='AquariusZodiacOverview'),
    path('ZodiacOverallview/PiscesZodiac/',views.PiscesZodiacOverviewDetailView,name='PiscesZodiacOverview'),

    path('MyZodiacCareers/',views.ZodiacCareerDetailView,name='MyZodiacCareerDetails'),
    path('MyZodiacCareers/AriesCareers/',views.AriesZodiacCareerDetailView,name="AriesZodiacCareerDetails"),
    path('MyZodiacCareers/TaurusCareers/',views.TaurusZodiacCareerDetailView,name="TaurusZodiacCareerDetails"),
    path('MyZodiacCareers/GeminiCareers/',views.GeminiZodiacCareerDetailView,name="GeminiZodiacCareerDetails"),
    path('MyZodiacCareers/CancerCareers/',views.CancerZodiacCareerDetailView,name="CancerZodiacCareerDetails"),
    path('MyZodiacCareers/LeoCareers/',views.LeoZodiacCareerDetailView,name="LeoZodiacCareerDetails"),
    path('MyZodiacCareers/VirgoCareers/',views.VirgoZodiacCareerDetailView,name="VirgoZodiacCareerDetails"),
    path('MyZodiacCareers/LibraCareers/',views.LibraZodiacCareerDetailView,name="LibraZodiacCareerDetails"),
    path('MyZodiacCareers/ScorpioCareers/',views.ScorpioZodiacCareerDetailView,name="ScorpioZodiacCareerDetails"),
    path('MyZodiacCareers/SagittariusCareers/',views.SagittariusZodiacCareerDetailView,name="SagittariusZodiacCareerDetails"),
    path('MyZodiacCareers/CapricornCareers/',views.CapricornZodiacCareerDetailView,name="CapricornZodiacCareerDetails"),
    path('MyZodiacCareers/AquariusCareers/',views.AquariusZodiacCareerDetailView,name="AquariusZodiacCareerDetails"),
    path('MyZodiacCareers/PiscesCareers/',views.PiscesZodiacCareerDetailView,name="PiscesZodiacCareerDetails"),
    
    path('MyZodiacHealth/',views.ZodiacHealthDetailView,name='MyZodiacHealthDetails'),
    path('MyZodiacHealth/AriesHealth/',views.AriesZodiacHealthDetailView,name="AriesZodiacHealthDetails"),
    path('MyZodiacHealth/TaurusHealth/',views.TaurusZodiacHealthDetailView,name="TaurusZodiacHealthDetails"),
    path('MyZodiacHealth/GeminiHealth/',views.GeminiZodiacHealthDetailView,name="GeminiZodiacHealthDetails"),
    path('MyZodiacHealth/CancerHealth/',views.CancerZodiacHealthDetailView,name="CancerZodiacHealthDetails"),
    path('MyZodiacHealth/LeoHealth/',views.LeoZodiacHealthDetailView,name="LeoZodiacHealthDetails"),
    path('MyZodiacHealth/VirgoHealth/',views.VirgoZodiacHealthDetailView,name="VirgoZodiacHealthDetails"),
    path('MyZodiacHealth/LibraHealth/',views.LibraZodiacHealthDetailView,name="LibraZodiacHealthDetails"),
    path('MyZodiacHealth/ScorpioHealth/',views.ScorpioZodiacHealthDetailView,name="ScorpioZodiacHealthDetails"),
    path('MyZodiacHealth/SagittariusHealth/',views.SagittariusZodiacHealthDetailView,name="SagittariusZodiacHealthDetails"),
    path('MyZodiacHealth/CapricornHealth/',views.CapricornZodiacHealthDetailView,name="CapricornZodiacHealthDetails"),
    path('MyZodiacHealth/AquariusHealth/',views.AquariusZodiacHealthDetailView,name="AquariusZodiacHealthDetails"),
    path('MyZodiacHealth/PiscesHealth/',views.PiscesZodiacHealthDetailView,name="PiscesZodiacHealthDetails"),

    path('MyZodiacLove/',views.ZodiacLoveDetailView,name='MyZodiacLoveDetails'),
    path('MyZodiacLove/AriesLove/',views.AriesZodiacLoveDetailView,name='AriesZodiacLoveDetails'),
    path('MyZodiacLove/TaurusLove/',views.TaurusZodiacLoveDetailView,name='TaurusZodiacLoveDetails'),
    path('MyZodiacLove/GeminiLove/',views.GeminiZodiacLoveDetailView,name='GeminiZodiacLoveDetails'),
    path('MyZodiacLove/CancerLove/',views.CancerZodiacLoveDetailView,name='CancerZodiacLoveDetails'),
    path('MyZodiacLove/LeoLove/',views.LeoZodiacLoveDetailView,name='LeoZodiacLoveDetails'),
    path('MyZodiacLove/VirgoLove/',views.VirgoZodiacLoveDetailView,name='VirgoZodiacLoveDetails'),
    path('MyZodiacLove/LibraLove/',views.LibraZodiacLoveDetailView,name='LibraZodiacLoveDetails'),
    path('MyZodiacLove/ScorpioLove/',views.ScorpioZodiacLoveDetailView,name='ScorpioZodiacLoveDetails'),
    path('MyZodiacLove/SagittariusLove/',views.SagittariusZodiacLoveDetailView,name='SagittariusZodiacLoveDetails'),
    path('MyZodiacLove/CapricornLove/',views.CapricornZodiacLoveDetailView,name='CapricornZodiacLoveDetails'),
    path('MyZodiacLove/AquariusLove/',views.AquariusZodiacLoveDetailView,name='AquariusZodiacLoveDetails'),
    path('MyZodiacLove/PiscesLove/',views.PiscesZodiacLoveDetailView,name='PiscesZodiacLoveDetails'),
    
    path('MyZodiacMoney/',views.ZodiacMoneyDetailView,name='MyZodiacMoneyDetails'),
    path('MyZodiacMoney/AriesMoney/',views.AriesZodiacMoneyDetailView,name='AriesZodiacMoneyDetail'),
    path('MyZodiacMoney/TaurusMoney/',views.TaurusZodiacMoneyDetailView,name='TaurusZodiacMoneyDetail'),
    path('MyZodiacMoney/GeminiMoney/',views.GeminiZodiacMoneyDetailView,name='GeminiZodiacMoneyDetail'),
    path('MyZodiacMoney/CancerMoney/',views.CancerZodiacMoneyDetailView,name='CancerZodiacMoneyDetail'),
    path('MyZodiacMoney/LeoMoney/',views.LeoZodiacMoneyDetailView,name='LeoZodiacMoneyDetail'),
    path('MyZodiacMoney/VirgoMoney/',views.VirgoZodiacMoneyDetailView,name='VirgoZodiacMoneyDetail'),
    path('MyZodiacMoney/LibraMoney/',views.LibraZodiacMoneyDetailView,name='LibraZodiacMoneyDetail'),
    path('MyZodiacMoney/ScorpioMoney/',views.ScorpioZodiacMoneyDetailView,name='ScorpioZodiacMoneyDetail'),
    path('MyZodiacMoney/SagittariusMoney/',views.SagittariusZodiacMoneyDetailView,name='SagittariusZodiacMoneyDetail'),
    path('MyZodiacMoney/CapricornMoney/',views.CapricornZodiacMoneyDetailView,name='CapricornZodiacMoneyDetail'),
    path('MyZodiacMoney/AquariusMoney/',views.AquariusZodiacMoneyDetailView,name='AquariusZodiacMoneyDetail'),
    path('MyZodiacMoney/PiscesMoney/',views.PiscesZodiacMoneyDetailView,name='PiscesZodiacMoneyDetail'),
    
    path('MyZodiacRetail/',views.ZodiacRetailDetailView,name='MyZodiacRetailDetails'),
    path('MyZodiacRetail/AriesRetail/',views.AriesZodiacRetailDetailView,name='AriesZodiacRetailDetails'),
    path('MyZodiacRetail/TaurusRetail/',views.TaurusZodiacRetailDetailView,name='TaurusZodiacRetailDetails'),
    path('MyZodiacRetail/GeminiRetail/',views.GeminiZodiacRetailDetailView,name='GeminiZodiacRetailDetails'),
    path('MyZodiacRetail/CancerRetail/',views.CancerZodiacRetailDetailView,name='CancerZodiacRetailDetails'),
    path('MyZodiacRetail/LeoRetail/',views.LeoZodiacRetailDetailView,name='LeoZodiacRetailDetails'),
    path('MyZodiacRetail/VirgoRetail/',views.VirgoZodiacRetailDetailView,name='VirgoZodiacRetailDetails'),
    path('MyZodiacRetail/LibraRetail/',views.LibraZodiacRetailDetailView,name='LibraZodiacRetailDetails'),
    path('MyZodiacRetail/ScorpioRetail/',views.ScorpioZodiacRetailDetailView,name='ScorpioZodiacRetailDetails'),
    path('MyZodiacRetail/SagittariusRetail/',views.SagittariusZodiacRetailDetailView,name='SagittariusZodiacRetailDetails'),
    path('MyZodiacRetail/CapricornRetail/',views.CapricornZodiacRetailDetailView,name='CapricornZodiacRetailDetails'),
    path('MyZodiacRetail/AquariusRetail/',views.AquariusZodiacRetailDetailView,name='AquariusZodiacRetailDetails'),
    path('MyZodiacRetail/PiscesRetail/',views.PiscesZodiacRetailDetailView,name='PiscesZodiacRetailDetails'),
]